export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REFRESHTOKEN_REQUEST = 'REFRESHTOKEN_REQUEST';
export const REFRESHTOKEN_SUCCESS = 'REFRESHTOKEN_SUCCESS';
export const REFRESHTOKEN_FAILURE = 'REFRESHTOKEN_FAILURE';


export const CONSULTATION_REQUEST = 'CONSULTATION_REQUEST';
export const CONSULTATION_SUCCESS = 'CONSULTATION_SUCCESS';
export const CONSULTATION_FAILURE = 'CONSULTATION_FAILURE';
export const CONSULTATION_DETAIL_SUCCESS = 'CONSULTATION_DETAIL_SUCCESS';
export const CONSULTATION_DETAIL_EMPTY = 'CONSULTATION_DETAIL_EMPTY';



